services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: budget
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user -d budget"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: [.env]
    depends_on:
      db:
        condition: service_healthy
    # Порт наружу больше не публикуем: Caddy — фронтовой вход
    # ports:
    #   - "8000:8000"
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./app/static:/srv/gui:ro   # GUI-статик, который будет отдавать Caddy
    restart: unless-stopped

volumes:
  db_data: