version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: budget
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user -d budget"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [internal]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: [.env]
    depends_on:
      db:
        condition: service_healthy
    # API НЕ публикуем наружу — доступ только через Caddy
    restart: unless-stopped
    networks: [internal]

  caddy:
    image: caddy:2
    depends_on:
      api:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Твой Caddyfile из репозитория
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # Статика GUI, которую Caddy отдаёт на /
      - ./app/static:/srv/gui:ro
      # Служебные тома для сертификатов/конфига
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks: [internal]

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge